// Especifica la versión de la sintaxis de Protocol Buffers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.26.1
// source: msg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MichaelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         string                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MichaelRequest) Reset() {
	*x = MichaelRequest{}
	mi := &file_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MichaelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MichaelRequest) ProtoMessage() {}

func (x *MichaelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MichaelRequest.ProtoReflect.Descriptor instead.
func (*MichaelRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MichaelRequest) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

type MichaelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Botin         uint64                 `protobuf:"varint,1,opt,name=botin,proto3" json:"botin,omitempty"`
	PFranklin     int32                  `protobuf:"varint,2,opt,name=pFranklin,proto3" json:"pFranklin,omitempty"`
	PTrevor       int32                  `protobuf:"varint,3,opt,name=pTrevor,proto3" json:"pTrevor,omitempty"`
	RPolicial     int32                  `protobuf:"varint,4,opt,name=rPolicial,proto3" json:"rPolicial,omitempty"`
	POferta       string                 `protobuf:"bytes,5,opt,name=pOferta,proto3" json:"pOferta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MichaelResponse) Reset() {
	*x = MichaelResponse{}
	mi := &file_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MichaelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MichaelResponse) ProtoMessage() {}

func (x *MichaelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MichaelResponse.ProtoReflect.Descriptor instead.
func (*MichaelResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MichaelResponse) GetBotin() uint64 {
	if x != nil {
		return x.Botin
	}
	return 0
}

func (x *MichaelResponse) GetPFranklin() int32 {
	if x != nil {
		return x.PFranklin
	}
	return 0
}

func (x *MichaelResponse) GetPTrevor() int32 {
	if x != nil {
		return x.PTrevor
	}
	return 0
}

func (x *MichaelResponse) GetRPolicial() int32 {
	if x != nil {
		return x.RPolicial
	}
	return 0
}

func (x *MichaelResponse) GetPOferta() string {
	if x != nil {
		return x.POferta
	}
	return ""
}

type TrevorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notificar     string                 `protobuf:"bytes,1,opt,name=notificar,proto3" json:"notificar,omitempty"`
	PTrevor       int32                  `protobuf:"varint,2,opt,name=pTrevor,proto3" json:"pTrevor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrevorRequest) Reset() {
	*x = TrevorRequest{}
	mi := &file_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrevorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrevorRequest) ProtoMessage() {}

func (x *TrevorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrevorRequest.ProtoReflect.Descriptor instead.
func (*TrevorRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *TrevorRequest) GetNotificar() string {
	if x != nil {
		return x.Notificar
	}
	return ""
}

func (x *TrevorRequest) GetPTrevor() int32 {
	if x != nil {
		return x.PTrevor
	}
	return 0
}

type TrevorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resultado     string                 `protobuf:"bytes,1,opt,name=resultado,proto3" json:"resultado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrevorResponse) Reset() {
	*x = TrevorResponse{}
	mi := &file_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrevorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrevorResponse) ProtoMessage() {}

func (x *TrevorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrevorResponse.ProtoReflect.Descriptor instead.
func (*TrevorResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *TrevorResponse) GetResultado() string {
	if x != nil {
		return x.Resultado
	}
	return ""
}

type FranklinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notificar     string                 `protobuf:"bytes,1,opt,name=notificar,proto3" json:"notificar,omitempty"`
	PFranklin     int32                  `protobuf:"varint,2,opt,name=pFranklin,proto3" json:"pFranklin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FranklinRequest) Reset() {
	*x = FranklinRequest{}
	mi := &file_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FranklinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FranklinRequest) ProtoMessage() {}

func (x *FranklinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FranklinRequest.ProtoReflect.Descriptor instead.
func (*FranklinRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *FranklinRequest) GetNotificar() string {
	if x != nil {
		return x.Notificar
	}
	return ""
}

func (x *FranklinRequest) GetPFranklin() int32 {
	if x != nil {
		return x.PFranklin
	}
	return 0
}

type FranklinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resultado     string                 `protobuf:"bytes,1,opt,name=resultado,proto3" json:"resultado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FranklinResponse) Reset() {
	*x = FranklinResponse{}
	mi := &file_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FranklinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FranklinResponse) ProtoMessage() {}

func (x *FranklinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FranklinResponse.ProtoReflect.Descriptor instead.
func (*FranklinResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{5}
}

func (x *FranklinResponse) GetResultado() string {
	if x != nil {
		return x.Resultado
	}
	return ""
}

// Nuevos mensajes para Fase 3
type GolpeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Personaje      string                 `protobuf:"bytes,1,opt,name=personaje,proto3" json:"personaje,omitempty"`
	Probabilidad   int32                  `protobuf:"varint,2,opt,name=probabilidad,proto3" json:"probabilidad,omitempty"`
	RiesgoPolicial int32                  `protobuf:"varint,3,opt,name=riesgoPolicial,proto3" json:"riesgoPolicial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GolpeRequest) Reset() {
	*x = GolpeRequest{}
	mi := &file_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolpeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolpeRequest) ProtoMessage() {}

func (x *GolpeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolpeRequest.ProtoReflect.Descriptor instead.
func (*GolpeRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{6}
}

func (x *GolpeRequest) GetPersonaje() string {
	if x != nil {
		return x.Personaje
	}
	return ""
}

func (x *GolpeRequest) GetProbabilidad() int32 {
	if x != nil {
		return x.Probabilidad
	}
	return 0
}

func (x *GolpeRequest) GetRiesgoPolicial() int32 {
	if x != nil {
		return x.RiesgoPolicial
	}
	return 0
}

type GolpeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Exito            bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	MotivoFallo      string                 `protobuf:"bytes,2,opt,name=motivoFallo,proto3" json:"motivoFallo,omitempty"`
	BotinExtra       int64                  `protobuf:"varint,3,opt,name=botinExtra,proto3" json:"botinExtra,omitempty"`
	EstrellasFinales int32                  `protobuf:"varint,4,opt,name=estrellasFinales,proto3" json:"estrellasFinales,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GolpeResponse) Reset() {
	*x = GolpeResponse{}
	mi := &file_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolpeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolpeResponse) ProtoMessage() {}

func (x *GolpeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolpeResponse.ProtoReflect.Descriptor instead.
func (*GolpeResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{7}
}

func (x *GolpeResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *GolpeResponse) GetMotivoFallo() string {
	if x != nil {
		return x.MotivoFallo
	}
	return ""
}

func (x *GolpeResponse) GetBotinExtra() int64 {
	if x != nil {
		return x.BotinExtra
	}
	return 0
}

func (x *GolpeResponse) GetEstrellasFinales() int32 {
	if x != nil {
		return x.EstrellasFinales
	}
	return 0
}

type EstrellasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personaje     string                 `protobuf:"bytes,1,opt,name=personaje,proto3" json:"personaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstrellasRequest) Reset() {
	*x = EstrellasRequest{}
	mi := &file_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstrellasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstrellasRequest) ProtoMessage() {}

func (x *EstrellasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstrellasRequest.ProtoReflect.Descriptor instead.
func (*EstrellasRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{8}
}

func (x *EstrellasRequest) GetPersonaje() string {
	if x != nil {
		return x.Personaje
	}
	return ""
}

type EstrellasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estrellas     int32                  `protobuf:"varint,1,opt,name=estrellas,proto3" json:"estrellas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstrellasResponse) Reset() {
	*x = EstrellasResponse{}
	mi := &file_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstrellasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstrellasResponse) ProtoMessage() {}

func (x *EstrellasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstrellasResponse.ProtoReflect.Descriptor instead.
func (*EstrellasResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{9}
}

func (x *EstrellasResponse) GetEstrellas() int32 {
	if x != nil {
		return x.Estrellas
	}
	return 0
}

type NotificacionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Personaje      string                 `protobuf:"bytes,1,opt,name=personaje,proto3" json:"personaje,omitempty"`
	RiesgoPolicial int32                  `protobuf:"varint,2,opt,name=riesgoPolicial,proto3" json:"riesgoPolicial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificacionRequest) Reset() {
	*x = NotificacionRequest{}
	mi := &file_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificacionRequest) ProtoMessage() {}

func (x *NotificacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificacionRequest.ProtoReflect.Descriptor instead.
func (*NotificacionRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{10}
}

func (x *NotificacionRequest) GetPersonaje() string {
	if x != nil {
		return x.Personaje
	}
	return ""
}

func (x *NotificacionRequest) GetRiesgoPolicial() int32 {
	if x != nil {
		return x.RiesgoPolicial
	}
	return 0
}

type NotificacionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iniciado      bool                   `protobuf:"varint,1,opt,name=iniciado,proto3" json:"iniciado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificacionResponse) Reset() {
	*x = NotificacionResponse{}
	mi := &file_msg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificacionResponse) ProtoMessage() {}

func (x *NotificacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificacionResponse.ProtoReflect.Descriptor instead.
func (*NotificacionResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{11}
}

func (x *NotificacionResponse) GetIniciado() bool {
	if x != nil {
		return x.Iniciado
	}
	return false
}

type DetenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personaje     string                 `protobuf:"bytes,1,opt,name=personaje,proto3" json:"personaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetenerRequest) Reset() {
	*x = DetenerRequest{}
	mi := &file_msg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetenerRequest) ProtoMessage() {}

func (x *DetenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetenerRequest.ProtoReflect.Descriptor instead.
func (*DetenerRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{12}
}

func (x *DetenerRequest) GetPersonaje() string {
	if x != nil {
		return x.Personaje
	}
	return ""
}

type DetenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detenido      bool                   `protobuf:"varint,1,opt,name=detenido,proto3" json:"detenido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetenerResponse) Reset() {
	*x = DetenerResponse{}
	mi := &file_msg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetenerResponse) ProtoMessage() {}

func (x *DetenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetenerResponse.ProtoReflect.Descriptor instead.
func (*DetenerResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{13}
}

func (x *DetenerResponse) GetDetenido() bool {
	if x != nil {
		return x.Detenido
	}
	return false
}

type BotinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personaje     string                 `protobuf:"bytes,1,opt,name=personaje,proto3" json:"personaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotinRequest) Reset() {
	*x = BotinRequest{}
	mi := &file_msg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotinRequest) ProtoMessage() {}

func (x *BotinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotinRequest.ProtoReflect.Descriptor instead.
func (*BotinRequest) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{14}
}

func (x *BotinRequest) GetPersonaje() string {
	if x != nil {
		return x.Personaje
	}
	return ""
}

type BotinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotinTotal    int64                  `protobuf:"varint,1,opt,name=botinTotal,proto3" json:"botinTotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotinResponse) Reset() {
	*x = BotinResponse{}
	mi := &file_msg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotinResponse) ProtoMessage() {}

func (x *BotinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotinResponse.ProtoReflect.Descriptor instead.
func (*BotinResponse) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{15}
}

func (x *BotinResponse) GetBotinTotal() int64 {
	if x != nil {
		return x.BotinTotal
	}
	return 0
}

var File_msg_proto protoreflect.FileDescriptor

const file_msg_proto_rawDesc = "" +
	"\n" +
	"\tmsg.proto\"&\n" +
	"\x0eMichaelRequest\x12\x14\n" +
	"\x05offer\x18\x01 \x01(\tR\x05offer\"\x97\x01\n" +
	"\x0fMichaelResponse\x12\x14\n" +
	"\x05botin\x18\x01 \x01(\x04R\x05botin\x12\x1c\n" +
	"\tpFranklin\x18\x02 \x01(\x05R\tpFranklin\x12\x18\n" +
	"\apTrevor\x18\x03 \x01(\x05R\apTrevor\x12\x1c\n" +
	"\trPolicial\x18\x04 \x01(\x05R\trPolicial\x12\x18\n" +
	"\apOferta\x18\x05 \x01(\tR\apOferta\"G\n" +
	"\rTrevorRequest\x12\x1c\n" +
	"\tnotificar\x18\x01 \x01(\tR\tnotificar\x12\x18\n" +
	"\apTrevor\x18\x02 \x01(\x05R\apTrevor\".\n" +
	"\x0eTrevorResponse\x12\x1c\n" +
	"\tresultado\x18\x01 \x01(\tR\tresultado\"M\n" +
	"\x0fFranklinRequest\x12\x1c\n" +
	"\tnotificar\x18\x01 \x01(\tR\tnotificar\x12\x1c\n" +
	"\tpFranklin\x18\x02 \x01(\x05R\tpFranklin\"0\n" +
	"\x10FranklinResponse\x12\x1c\n" +
	"\tresultado\x18\x01 \x01(\tR\tresultado\"x\n" +
	"\fGolpeRequest\x12\x1c\n" +
	"\tpersonaje\x18\x01 \x01(\tR\tpersonaje\x12\"\n" +
	"\fprobabilidad\x18\x02 \x01(\x05R\fprobabilidad\x12&\n" +
	"\x0eriesgoPolicial\x18\x03 \x01(\x05R\x0eriesgoPolicial\"\x93\x01\n" +
	"\rGolpeResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12 \n" +
	"\vmotivoFallo\x18\x02 \x01(\tR\vmotivoFallo\x12\x1e\n" +
	"\n" +
	"botinExtra\x18\x03 \x01(\x03R\n" +
	"botinExtra\x12*\n" +
	"\x10estrellasFinales\x18\x04 \x01(\x05R\x10estrellasFinales\"0\n" +
	"\x10EstrellasRequest\x12\x1c\n" +
	"\tpersonaje\x18\x01 \x01(\tR\tpersonaje\"1\n" +
	"\x11EstrellasResponse\x12\x1c\n" +
	"\testrellas\x18\x01 \x01(\x05R\testrellas\"[\n" +
	"\x13NotificacionRequest\x12\x1c\n" +
	"\tpersonaje\x18\x01 \x01(\tR\tpersonaje\x12&\n" +
	"\x0eriesgoPolicial\x18\x02 \x01(\x05R\x0eriesgoPolicial\"2\n" +
	"\x14NotificacionResponse\x12\x1a\n" +
	"\biniciado\x18\x01 \x01(\bR\biniciado\".\n" +
	"\x0eDetenerRequest\x12\x1c\n" +
	"\tpersonaje\x18\x01 \x01(\tR\tpersonaje\"-\n" +
	"\x0fDetenerResponse\x12\x1a\n" +
	"\bdetenido\x18\x01 \x01(\bR\bdetenido\",\n" +
	"\fBotinRequest\x12\x1c\n" +
	"\tpersonaje\x18\x01 \x01(\tR\tpersonaje\"/\n" +
	"\rBotinResponse\x12\x1e\n" +
	"\n" +
	"botinTotal\x18\x01 \x01(\x03R\n" +
	"botinTotal2\xc4\x01\n" +
	"\rLesterService\x121\n" +
	"\fMichaelOffer\x12\x0f.MichaelRequest\x1a\x10.MichaelResponse\x12D\n" +
	"\x15IniciarNotificaciones\x12\x14.NotificacionRequest\x1a\x15.NotificacionResponse\x12:\n" +
	"\x15DetenerNotificaciones\x12\x0f.DetenerRequest\x1a\x10.DetenerResponse2\xda\x01\n" +
	"\rTrevorService\x12.\n" +
	"\vDistraccion\x12\x0e.TrevorRequest\x1a\x0f.TrevorResponse\x12-\n" +
	"\fIniciarGolpe\x12\r.GolpeRequest\x1a\x0e.GolpeResponse\x12;\n" +
	"\x12ConsultarEstrellas\x12\x11.EstrellasRequest\x1a\x12.EstrellasResponse\x12-\n" +
	"\fObtenerBotin\x12\r.BotinRequest\x1a\x0e.BotinResponse2\xe0\x01\n" +
	"\x0fFranklinService\x122\n" +
	"\vDistraccion\x12\x10.FranklinRequest\x1a\x11.FranklinResponse\x12-\n" +
	"\fIniciarGolpe\x12\r.GolpeRequest\x1a\x0e.GolpeResponse\x12;\n" +
	"\x12ConsultarEstrellas\x12\x11.EstrellasRequest\x1a\x12.EstrellasResponse\x12-\n" +
	"\fObtenerBotin\x12\r.BotinRequest\x1a\x0e.BotinResponseB\x14Z\x12./grpc/proto;protob\x06proto3"

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData []byte
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)))
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_msg_proto_goTypes = []any{
	(*MichaelRequest)(nil),       // 0: MichaelRequest
	(*MichaelResponse)(nil),      // 1: MichaelResponse
	(*TrevorRequest)(nil),        // 2: TrevorRequest
	(*TrevorResponse)(nil),       // 3: TrevorResponse
	(*FranklinRequest)(nil),      // 4: FranklinRequest
	(*FranklinResponse)(nil),     // 5: FranklinResponse
	(*GolpeRequest)(nil),         // 6: GolpeRequest
	(*GolpeResponse)(nil),        // 7: GolpeResponse
	(*EstrellasRequest)(nil),     // 8: EstrellasRequest
	(*EstrellasResponse)(nil),    // 9: EstrellasResponse
	(*NotificacionRequest)(nil),  // 10: NotificacionRequest
	(*NotificacionResponse)(nil), // 11: NotificacionResponse
	(*DetenerRequest)(nil),       // 12: DetenerRequest
	(*DetenerResponse)(nil),      // 13: DetenerResponse
	(*BotinRequest)(nil),         // 14: BotinRequest
	(*BotinResponse)(nil),        // 15: BotinResponse
}
var file_msg_proto_depIdxs = []int32{
	0,  // 0: LesterService.MichaelOffer:input_type -> MichaelRequest
	10, // 1: LesterService.IniciarNotificaciones:input_type -> NotificacionRequest
	12, // 2: LesterService.DetenerNotificaciones:input_type -> DetenerRequest
	2,  // 3: TrevorService.Distraccion:input_type -> TrevorRequest
	6,  // 4: TrevorService.IniciarGolpe:input_type -> GolpeRequest
	8,  // 5: TrevorService.ConsultarEstrellas:input_type -> EstrellasRequest
	14, // 6: TrevorService.ObtenerBotin:input_type -> BotinRequest
	4,  // 7: FranklinService.Distraccion:input_type -> FranklinRequest
	6,  // 8: FranklinService.IniciarGolpe:input_type -> GolpeRequest
	8,  // 9: FranklinService.ConsultarEstrellas:input_type -> EstrellasRequest
	14, // 10: FranklinService.ObtenerBotin:input_type -> BotinRequest
	1,  // 11: LesterService.MichaelOffer:output_type -> MichaelResponse
	11, // 12: LesterService.IniciarNotificaciones:output_type -> NotificacionResponse
	13, // 13: LesterService.DetenerNotificaciones:output_type -> DetenerResponse
	3,  // 14: TrevorService.Distraccion:output_type -> TrevorResponse
	7,  // 15: TrevorService.IniciarGolpe:output_type -> GolpeResponse
	9,  // 16: TrevorService.ConsultarEstrellas:output_type -> EstrellasResponse
	15, // 17: TrevorService.ObtenerBotin:output_type -> BotinResponse
	5,  // 18: FranklinService.Distraccion:output_type -> FranklinResponse
	7,  // 19: FranklinService.IniciarGolpe:output_type -> GolpeResponse
	9,  // 20: FranklinService.ConsultarEstrellas:output_type -> EstrellasResponse
	15, // 21: FranklinService.ObtenerBotin:output_type -> BotinResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
